# Generated by Django 5.0.3 on 2024-03-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0002_recipeitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChefRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine', models.TextField()),
                ('time', models.TextField()),
                ('steps', models.TextField()),
                ('description', models.TextField()),
                ('ingredients', models.TextField()),
                ('field7', models.TextField()),
            ],
        ),
    ]
