# Generated by Django 5.0.3 on 2024-04-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0003_chefrecipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grains_and_flours', models.CharField(max_length=100)),
                ('nuts_and_seeds', models.CharField(max_length=100)),
                ('sweeteners', models.CharField(max_length=100)),
                ('dairy_and_egg_products', models.CharField(max_length=100)),
                ('proteins', models.CharField(max_length=100)),
                ('condiments_and_sauces', models.CharField(max_length=100)),
                ('herbs_spices_and_seasonings', models.CharField(max_length=100)),
                ('fruits', models.CharField(max_length=100)),
                ('vegetables', models.CharField(max_length=100)),
                ('miscellaneous', models.CharField(max_length=100)),
            ],
        ),
    ]
